### PR TITLE
remove everything except camel

### PR DESCRIPTION
**Pull request by vaikas**
Removing all the code except camel. Cleanup after hoisting the entire eventing-contrib repo here.

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by vaikas** [comment]
@nicolaferraro

**Review by nicolaferraro — COMMENTED** [review]
Thanks @vaikas. I think there are other dirs that can be cleaned up as well:

- cmd
- config
- samples
- test/performance

**Comment by vaikas** [comment]
Cool cool. I was actually going to ask you, but I think we want to flatten the dirs structure a bit? There's really no need to have camel/source and was going to follow up with a rejiggering of the dirs. Kind of like what we do here:
https://github.com/knative-sandbox/eventing-rabbitmq/

So, then it looks and feels like all the other repos. Thoughts @nicolaferraro

**Comment by nicolaferraro** [comment]
> Cool cool. I was actually going to ask you, but I think we want to flatten the dirs structure a bit? There's really no need to have camel/source and was going to follow up with a rejiggering of the dirs. Kind of like what we do here:
> https://github.com/knative-sandbox/eventing-rabbitmq/
> 
> So, then it looks and feels like all the other repos. Thoughts @nicolaferraro

Yes, right. Now that those dirs dirs are no longer present, the ones under camel/source/... can be moved to the root.

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
